### ISSUE TITLE
location selling extra components

### ISSUE THREAD

**Issue by knmcguire** [tristandijkstra/CrazyFlieGimbal#1]
Hi! 

Could you perhaps share where you ordered the components from you need next to the 3d printed components? The ball bearings are of a size that is a bit difficult to find for our users (I'm assuming that the sizes indicated are in millimeters?)

https://github.com/tristandijkstra/OpenGimbal#parts

**Comment by tristandijkstra** [comment]
Hi Kimberly,

The parts are all in milimeters yes. I ordered the originals from Conrad:

- https://www.conrad.nl/nl/p/reely-miniatuur-kogellager-chroomstaal-binnendiameter-3-mm-buitendiameter-9-mm-toerental-max-65000-omw-min-221985.html
- https://www.conrad.nl/nl/p/reely-rc-auto-kogellager-chroomstaal-binnendiameter-6-mm-buitendiameter-12-mm-toerental-max-43000-omw-min-295612.html#productDescription

I've seen similar sizes on RS as well:
- https://nl.rs-online.com/web/c/bearings-seals/rotary-bearings-housing-units/ball-bearings/?applied-dimensions=4294830973,4294871505

Hopefully this helps?

**Comment by knmcguire** [comment]
Ah, thanks, super helpful! I was getting a bit worried as digikey and Amazon didn't show many options, but I forgot about Conrad!
